services:
  mariadb:
    container_name: mariadb
    image: mariadb:inception # image tagging
    build:
      context: ./requirements/mariadb
    env_file: .env
#    environment:
#      MYSQL_ROOT_PASSWORD: rtpass
#      MYSQL_DATABASE: wordpress
#      MYSQL_USER: wpuser
#      MYSQL_PASSWORD: wppass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception # ????? Cal?

  wordpress:
    container_name: wordpress
    image: wordpress:inception # image tagging
    build:
      context: ./requirements/wordpress
    env_file: .env
    depends_on:
      - mariadb # ?
#    environment:
#      - WORDPRESS_DB_HOST=mariadb:3306 # Tells WordPress where to find MariaDB database. If not set WP by default looks for it in localhost
#      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
#      - WORDPRESS_DB_USER=${MYSQL_USER}
#      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - inception # ????? Cal?
    volumes:
      - wordpress_data:/var/www/html

volumes:
  mariadb_data:
  wordpress_data: # ?

networks:
  inception:
