services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb:inception
    environment:
      MYSQL_ROOT_PASSWORD: rtpass
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass
#    volumes:
#      - mariadb_data:/var/lib/mysql

#volumes:
#  mariadb_data:
